### ISSUE TITLE
Passing too small array to M3Det in curves.c

### ISSUE THREAD

**Issue by elfprince13** [deeice/lsynth#1]
> curve.c: In function 'matrix2quat':
> curve.c:507:23: warning: passing argument 1 of 'M3Det' from incompatible pointer type [-Wincompatible-pointer-types]
>    PRECISION D = M3Det(m);
>                        ^
> curve.c:468:11: note: expected 'float (*)[4]' but argument is of type 'float (*)[3]'
>  PRECISION M3Det(PRECISION m[3][4]) /* Note argument type !            */
>            ^~~~~
> gcc -ggdb   -c -o mathlib.o mathlib.c

**Comment by deeice** [comment]
That's interesting.  Based on the comments it looks like maybe I did that on purpose as a hint that M3Det could be used on a 3x4 as well as 3x3. But it's apparently only used in one place, and that's with a 3x3 (rotation only, no translation).  Have C standards changed so much in the last 20 years that the technique no longer works?  If so, I suppose I could change M3Det to take a 3x3 instead.  But if it still works, I'd rather leave it.


--Don--


________________________________

**Comment by elfprince13** [comment]
If the definition of M3Det was `PRECISION M3Det(PRECISION m[4][3])` (instead of `PRECISION M3Det(PRECISION m[3][4])` as it currently stand)  I would expect it to work just fine, but in this case your index arithmetic is going to be off by one more in each successive row.

In other words, it's expecting this, and trying to access the left-most 3 columns:
```C
{{xx,xy,xz,xw},
 {yx,yy,yz,yw},
 {zx,zy,zz,zw}}
```
So if you give it this instead:
```C
{{xx,xy,xz},
 {yx,yy,yz},
 {zx,zy,zz}}
```
It will have the effect of reshaping it like this:
```C
{{xx,xy,xz,yx},
 {yy,yz,zx,zy},
 {zz,??,??,??}}
```

The standard hasn't changed *that* much in 20 years (though I much prefer C99 and C11 to C89), but compilers have gotten much better about telling you when your code isn't doing the thing you expect.

It's possible that an older compiler was decaying `PRECISION M3Det(PRECISION m[3][4])` into `PRECISION M3Det(PRECISION **m)`, rather than `PRECISION M3Det(PRECISION (*m)[4])`, in which case you get an extra layer of indirection and there's no reshaping effect, but, as far as I understand it, that would be incorrect behavior on the part of the compiler rather than a change in the C spec.

**Comment by deeice** [comment]
Ah, thanks.  I did some further digging and realized that was a function I pulled in from the L3p code in ldglite.  The comment actually was a warning to me from Lars, and I interpreted it wrong when I pasted the code into lsynth.  Function pointer and array of array syntax in C always seem backwards to me.  But this was in the days before stackoverflow so I must've looked it up and found a bad answer on the internet.

Anyhow, I see you've already moved ahead with a fork and pulled in the bricksmith changes.  That was on my todo list but I was probably never going to get around to it because it's been so long.  Keep going and and fix this.  That's why I moved the code to github, so someone motivated can more easily take it over, as I did long ago when Kevin ran out of steam.

**Comment by elfprince13** [comment]
Want me to PR changes back your way to keep it a bit more centralized?

**Comment by deeice** [comment]
Sure, pull requests would be fine.  There's an "easy" button now to merge those in, right?


--Don--


________________________________

**Comment by elfprince13** [comment]
Yep, you get a notification, and it opens a comment thread until you're happy with the contents, then you hit the merge button and it's all good.
